from algorunner.events import (
    AccountStatus, UpdateEvent, UpdateType
)


class Trader:
    """
    The Trader is a model of a real "trader" - i.e it monitors for indicators
    generated by it's strategy, applies calculations from rules defined by it's
    `Calculator` instance to determine whether an order should be made, and if
    so, at what rate/quantity.
    """

    def __call__(self, update_type: str, updated_props: UpdateEvent):
        """Sets account state - i.e. balance and positions."""

        if update_type == UpdateType.ACCOUNT:
            self.status = updated_props

        """
        # This required python > 3.10.*; alas there's a bug with pip
        # on this version. So this will likely need to be refactored
        # to use simple if/else comparisons until pip 21.2.3 is released.
        # @see https://github.com/pypa/pip/pull/10252
        # @todo
        match update_type:
            case UpdateType.BALANCE:
                # @todo Eh, look at whatever fuckery is involved.
                # surely the "Locked" balance needs updating to..?!
                asset = updated_props["Asset"]
                self.status.Positions[asset]["Free"] += updated_props["Update"]
            case UpdateType.ACCOUNT:
                self.status = updated_props
            case UpdateType.POSITION:
                self.status["Positions"] = updated_props
        """
        pass

    def initial_state(self, status: AccountStatus):
        self.status = status

    def start(self, handler):
        pass

    def balance(self, asset):
        return self.status.get(asset, None)


"""
    # @todo - these will be events.
    def buy(self, asset, amount, limit=False, price=0):
        if limit:
            self.binance.order_limit_buy(
                symbol=asset,
                quantity=amount,
                price=price)
        else:
            self.binance.order_market_buy(
                symbol=asset,
                quantity=amount)

    # @todo - these will be events.
    def sell(self, asset, amount, limit=False, price=0):
        if limit:
            self.binance.order_limit_sell(
                symbol=asset,
                quantity=amount,
                price=price)
        else:
            self.binance.order_market_sell(
                symbol=asset,
                quantity=amount)
"""
