# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: AlgoRunner

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9] # Py3 only, and latest release UP.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.7
    - name: Install dependencies
      run: |
        make deps
    - name: Run linting and tests
      run: |
        make ci
